# Exercise 7-2: Prepare the Cars Data

**CAP3321C - Data Wrangling**

---

## Overview

This exercise will guide you through the process of preparing the Cars data. You'll practice using lambda expressions and user-defined functions to add columns, then work with indexes and unstack data.

**Group Members:**
- Name 1: Ricardo
- Name 2:Elizabeth
- Name 3:Nicholas
- Name 4: Alex

---

## Read the Data

Run these cells to load the data.

In [1]:
import pandas as pd

In [2]:
# Download the data file from GitHub
!wget -q https://raw.githubusercontent.com/c-marq/CAP3321C-Data-Wrangling/main/data/cars.csv
print("Data file downloaded successfully!")

Data file downloaded successfully!

In [3]:
# Load the cars data
cars = pd.read_csv('cars.csv')
print("Data shape:", cars.shape)

Data shape: (205, 26)

### Task 4: Display the First Five Rows (YOUR CODE)

Display the first five rows of the DataFrame.

**Expected output:** Columns include car_ID, symboling, CarName, fueltype, etc.

In [4]:
# display first five rows
cars.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

---

## Part 1: Add and Drop Columns

Practice creating new columns using lambda expressions and user-defined functions.

### Task 5: Display Unique CarName Values (YOUR CODE)

Display the unique values for the `CarName` column.

**Hint:** Use the `unique()` method.

**Expected output:** Array of unique car names like 'alfa-romero giulia', 'audi 100 ls', etc.

In [5]:
# display unique CarName values
cars['CarName'].unique()

array(['alfa-romero giulia', 'alfa-romero stelvio',
       'alfa-romero Quadrifoglio', 'audi 100 ls', 'audi 100ls',
       'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)',
       'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5',
       'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300',
       'dodge rampage', 'dodge challenger se', 'dodge d200',
       'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)',
       'dodge coronet custom', 'dodge dart custom',
       'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc',
       'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl',
       'honda accord', 'honda civic 1300', 'honda prelude',
       'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ',
       'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk',
       'maxda rx3', 'maxda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4',
       'mazda glc deluxe', 'mazda 626', 'mazda glc', 'mazda rx-7 gs',
       'mazda glc 4', 'mazda glc custom l', 'mazda glc custom',
       'buick electra 225 custom', 'buick century luxus (sw)',
       'buick century', 'buick skyhawk', 'buick opel isuzu deluxe',
       'buick skylark', 'buick century special',
       'buick regal sport coupe (turbo)', 'mercury cougar',
       'mitsubishi mirage', 'mitsubishi lancer', 'mitsubishi outlander',
       'mitsubishi g4', 'mitsubishi mirage g4', 'mitsubishi montero',
       'mitsubishi pajero', 'Nissan versa', 'nissan gt-r', 'nissan rogue',
       'nissan latio', 'nissan titan', 'nissan leaf', 'nissan juke',
       'nissan note', 'nissan clipper', 'nissan nv200', 'nissan dayz',
       'nissan fuga', 'nissan otti', 'nissan teana', 'nissan kicks',
       'peugeot 504', 'peugeot 304', 'peugeot 504 (sw)', 'peugeot 604sl',
       'peugeot 505s turbo diesel', 'plymouth fury iii',
       'plymouth cricket', 'plymouth satellite custom (sw)',
       'plymouth fury gran sedan', 'plymouth valiant', 'plymouth duster',
       'porsche macan', 'porcshce panamera', 'porsche cayenne',
       'porsche boxter', 'renault 12tl', 'renault 5 gtl', 'saab 99e',
       'saab 99le', 'saab 99gle', 'subaru', 'subaru dl', 'subaru brz',
       'subaru baja', 'subaru r1', 'subaru r2', 'subaru trezia',
       'subaru tribeca', 'toyota corona mark ii', 'toyota corona',
       'toyota corolla 1200', 'toyota corona hardtop',
       'toyota corolla 1600 (sw)', 'toyota carina', 'toyota mark ii',
       'toyota corolla', 'toyota corolla liftback',
       'toyota celica gt liftback', 'toyota corolla tercel',
       'toyota corona liftback', 'toyota starlet', 'toyota tercel',
       'toyota cressida', 'toyota celica gt', 'toyouta tercel',
       'vokswagen rabbit', 'volkswagen 1131 deluxe sedan',
       'volkswagen model 111', 'volkswagen type 3', 'volkswagen 411 (sw)',
       'volkswagen super beetle', 'volkswagen dasher', 'vw dasher',
       'vw rabbit', 'volkswagen rabbit', 'volkswagen rabbit custom',
       'volvo 145e (sw)', 'volvo 144ea', 'volvo 244dl', 'volvo 245',
       'volvo 264gl', 'volvo diesel', 'volvo 246'], dtype=object)

### Task 6: Add Brand Column Using Lambda (YOUR CODE)

Add a column named `brand` that stores the brand of the car. To do that, use a **lambda expression** that calls the `split()` method to access portions of the strings in the `CarName` column.

**Hint:** The brand is the first word in CarName. Use `split(' ')[0]` to get the first word.

**Example syntax:**
```python
df['brand'] = df.apply(lambda x: x.CarName.split(' ')[0], axis=1)
```

**Expected output:** New 'brand' column containing just the brand name (e.g., 'alfa-romero', 'audi')

In [8]:
# add brand column using lambda
cars['brand'] = cars.apply(lambda x: x.CarName.split(' ')[0], axis=1)

In [9]:
cars[['CarName', 'brand']].head()

                    CarName        brand
0        alfa-romero giulia  alfa-romero
1       alfa-romero stelvio  alfa-romero
2  alfa-romero Quadrifoglio  alfa-romero
3               audi 100 ls         audi
4                audi 100ls         audi

### Task 7: Add Model Column Using a User-Defined Function (YOUR CODE)

Add a column named `model` that stores the car name without the brand. To do that, apply a **user-defined function** to each row.

**Hint:**
1. First, write a function that takes a row and returns everything after the first word in CarName
2. Use `split(' ')[1:]` to get all words after the first, then `' '.join()` to combine them

**Example syntax:**
```python
def get_model(row):
    words = row.CarName.split(' ')[1:]  # Get all words except first
    return ' '.join(words)              # Join them with spaces

df['model'] = df.apply(get_model, axis=1)
```

**Expected output:** New 'model' column containing the model name (e.g., 'giulia', '100 ls')

In [10]:
# get the model name
def get_model(row):
    words = row.CarName.split(' ')[1:]
    return ' '.join(words)

# add model column
cars['model'] = cars.apply(get_model, axis=1)

In [11]:
# Verify brand and model columns
cars[['CarName', 'brand', 'model']].head(10)

                    CarName        brand           model
0        alfa-romero giulia  alfa-romero          giulia
1       alfa-romero stelvio  alfa-romero         stelvio
2  alfa-romero Quadrifoglio  alfa-romero    Quadrifoglio
3               audi 100 ls         audi          100 ls
4                audi 100ls         audi           100ls
5                  audi fox         audi             fox
6                audi 100ls         audi           100ls
7                 audi 5000         audi            5000
8                 audi 4000         audi            4000
9       audi 5000s (diesel)         audi  5000s (diesel)

### Task 8: Drop the CarName and car_ID Columns (YOUR CODE)

Drop the `CarName` and `car_ID` columns since we now have the brand and model columns.

**Hint:** Use `drop(columns=[...])` with a list of column names.

**Example syntax:**
```python
df = df.drop(columns=['col1', 'col2'])
```

**Expected output:** DataFrame without CarName and car_ID columns

In [12]:
# drop CarName and car_ID columns
cars = cars.drop(columns=['CarName', 'car_ID'])

In [13]:
# Verify columns were dropped
cars.head()

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,brand,model
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero,giulia
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero,stelvio
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero,Quadrifoglio
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,3.19,3.40,10.0,102,5500,24,30,13950.0,audi,100 ls
4,2,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,3.19,3.40,8.0,115,5500,18,22,17450.0,audi,100ls

---

## Part 2: Set an Index and Unstack the Data

Practice filtering, indexing, and reshaping data.

### Task 9: Filter the Cars Data (YOUR CODE)

Filter the cars DataFrame by:
1. Getting only rows for **Volkswagen** brand
2. Getting only the columns named `model`, `horsepower`, `carbody`, and `doornumber`

Assign the new DataFrame to a variable named `cars_filtered` and display the first five rows.

**Hint:**
- Use `query()` to filter rows
- Use `[[column_list]]` to select columns
- Note: Brand may be spelled 'volkswagen' (check your unique values from earlier!)

**Example syntax:**
```python
cars_filtered = cars.query('brand == "volkswagen"')[['col1', 'col2', 'col3', 'col4']]
```

**Expected output:** DataFrame with only Volkswagen cars and 4 columns

In [15]:
# filter Volkswagen cars and select columns
cars_filtered = cars.query('brand == "volkswagen"')[
    ['model', 'horsepower', 'carbody', 'doornumber']
]

In [16]:
cars_filtered.head()

                 model  horsepower carbody doornumber
183  1131 deluxe sedan          85   sedan        two
184          model 111          52   sedan       four
185             type 3          85   sedan       four
186           411 (sw)          85   sedan       four
187       super beetle          68   sedan       four

### Task 10: Set an Index on cars_filtered (YOUR CODE)

Set an index on the `model`, `carbody`, and `doornumber` columns of the `cars_filtered` DataFrame. Assign the new DataFrame to a variable named `cars_indexed` and display it.

**Hint:** Use `set_index()` with a list of column names.

**Example syntax:**
```python
cars_indexed = cars_filtered.set_index(['col1', 'col2', 'col3'])
```

**Expected output:** DataFrame with a 3-level hierarchical index

In [18]:
# set index on model, carbody, and doornumber
cars_indexed = cars_filtered.set_index(
    ['model', 'carbody', 'doornumber']
)

cars_indexed

                                      horsepower
model             carbody doornumber
1131 deluxe sedan sedan   two                 85
model 111         sedan   four                52
type 3            sedan   four                85
411 (sw)          sedan   four                85
super beetle      sedan   four                68
dasher            sedan   four               100
rabbit            sedan   four               110
rabbit custom     sedan   four                68
dasher            wagon   four                88

### Task 11: Unstack the carbody Column (YOUR CODE)

Unstack the `carbody` column of the index. Note how this unstacks the carbody values (sedan and wagon) so they become columns, and how it adds NaN values to the wagon column where appropriate.

**Hint:** Use `unstack()` with the column name to unstack.

**Example syntax:**
```python
df_unstacked = df.unstack('column_name')
```

**Expected output:** Wide DataFrame with sedan and wagon as column headers under horsepower

In [19]:
# unstack the carbody column
cars_unstacked = cars_indexed.unstack('carbody')

In [22]:
cars_unstacked

                             horsepower
carbody                           sedan wagon
model             doornumber
1131 deluxe sedan two              85.0   NaN
411 (sw)          four             85.0   NaN
dasher            four            100.0  88.0
model 111         four             52.0   NaN
rabbit            four            110.0   NaN
rabbit custom     four             68.0   NaN
super beetle      four             68.0   NaN
type 3            four             85.0   NaN

---

## Summary

In this exercise, you practiced data preparation techniques:

**Adding Columns:**
- Lambda expressions with `apply()` and string methods
- User-defined functions with `apply()`

**Dropping Columns:**
- `drop(columns=[...])` - Remove unnecessary columns

**Filtering Data:**
- `query()` - Filter rows based on conditions
- `[[column_list]]` - Select specific columns

**Working with Indexes:**
- `set_index()` - Create hierarchical indexes
- `unstack()` - Pivot index levels to columns (creates NaN where data doesn't exist)

---

**Submission:** Save this notebook and submit to Canvas before the deadline.