In [1]:
import pandas as pd

# 6-1

Task 1

In [2]:
# read data
ramen = pd.read_csv('ramen-ratings.csv')

In [3]:
# show first five rows
ramen.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

In [4]:
#row count
ramen.shape

(2580, 7)

task 2

In [5]:
# rename Stars column
ramen = ramen.rename(columns={'Stars': 'Rating'})

In [6]:
ramen.head()

,Review #,Brand,Variety,Style,Country,Rating,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

task 3

In [7]:
# convert Style to category
ramen['Style'] = ramen['Style'].astype('category')

task 4

In [8]:
# drop Country column
ramen = ramen.drop(columns='Country')

task 5

In [9]:
# verify changes
ramen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  2580 non-null   int64
 1   Brand     2580 non-null   object
 2   Variety   2580 non-null   object
 3   Style     2578 non-null   category
 4   Rating    2580 non-null   object
 5   Top Ten   41 non-null     object
dtypes: category(1), int64(1), object(4)
memory usage: 103.8+ KB

task 6

In [11]:
# rename Brand and Variety columns
ramen = ramen.rename(columns={
    'Brand': 'Company',
    'Variety': 'Product'
})

In [12]:
ramen.head()

,Review #,Company,Product,Style,Rating,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,3.75,NaN

task 7

In [13]:
# show duplicate Company/Product rows
ramen[ramen.duplicated(subset=['Company', 'Product'], keep=False)]

,Review #,Company,Product,Style,Rating,Top Ten
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,2.25,NaN
24,2556,Ching's Secret,Hot Garlic Instant Noodles,Pack,4.25,NaN
47,2533,Nongshim,Shin Ramyun Black,Pack,5,NaN
70,2510,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,5,NaN
76,2504,Nongshim,Shin Ramyun,Pack,3,NaN
...,...,...,...,...,...,...
2548,32,Koka,Mi Hai Cua Crab Flavor,Pack,3.5,NaN
2555,25,Nissin,Demae Ramen Spicy Flavor,Pack,3,NaN
2559,21,Nongshim,Champong Oriental Noodles,Pack,4,NaN
2561,19,Nongshim,Shin Ramyun,Pack,4,NaN
2568,12,Sapporo Ichiban,Shrimp Flavor,Pack,2.5,NaN

task 8

In [14]:
# row count before dropping duplicates
ramen.shape[0]

2580

In [15]:
# drop duplicate
ramen = ramen.drop_duplicates(
    subset=['Company', 'Product'],
    keep='first'
)

In [16]:
# row count after dropping duplicates
ramen.shape[0]

2520

Task 9

In [17]:
# drop rows with missing values
ramen = ramen.dropna()

In [18]:
ramen.shape[0]

36

Task 10

In [19]:
# final verification
ramen.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36 entries, 616 to 2567
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  36 non-null     int64
 1   Company   36 non-null     object
 2   Product   36 non-null     object
 3   Style     36 non-null     category
 4   Rating    36 non-null     object
 5   Top Ten   36 non-null     object
dtypes: category(1), int64(1), object(4)
memory usage: 2.1+ KB

In [20]:
ramen.head()

,Review #,Company,Product,Style,Rating,Top Ten
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,5,2016 #10
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,5,2016 #1
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,5,2016 #8
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,5,2016 #5
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,5,2016 #9

# 6-2

Task 1

In [21]:
# read data
avocado = pd.read_csv('avocado.csv')

In [22]:
# first five rows
avocado.head()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

task 2

In [23]:
# check for missing values
avocado.isnull().sum()

Unnamed: 0      0
Date            0
AveragePrice    0
Total Volume    0
4046            0
4225            0
4770            0
Total Bags      0
Small Bags      0
Large Bags      0
XLarge Bags     0
type            0
year            0
region          0
dtype: int64

task 3

In [24]:
# show unique regions
avocado['region'].unique()

array(['Albany', 'Atlanta', 'BaltimoreWashington', 'Boise', 'Boston',
       'BuffaloRochester', 'California', 'Charlotte', 'Chicago',
       'CincinnatiDayton', 'Columbus', 'DallasFtWorth', 'Denver',
       'Detroit', 'GrandRapids', 'GreatLakes', 'HarrisburgScranton',
       'HartfordSpringfield', 'Houston', 'Indianapolis', 'Jacksonville',
       'LasVegas', 'LosAngeles', 'Louisville', 'MiamiFtLauderdale',
       'Midsouth', 'Nashville', 'NewOrleansMobile', 'NewYork',
       'Northeast', 'NorthernNewEngland', 'Orlando', 'Philadelphia',
       'PhoenixTucson', 'Pittsburgh', 'Plains', 'Portland',
       'RaleighGreensboro', 'RichmondNorfolk', 'Roanoke', 'Sacramento',
       'SanDiego', 'SanFrancisco', 'Seattle', 'SouthCarolina',
       'SouthCentral', 'Southeast', 'Spokane', 'StLouis', 'Syracuse',
       'Tampa', 'TotalUS', 'West', 'WestTexNewMexico'], dtype=object)

task 4

In [25]:
# row count before
before = avocado.shape[0]
before

18249

In [26]:
# drop TotalUS rows
avocado = avocado[avocado['region'] != 'TotalUS']

In [27]:
# rows dropped
before - avocado.shape[0]

338

task 5

In [28]:
# drop irrelevant columns
avocado = avocado.drop(
    columns=['Unnamed: 0', '4046', '4225', '4770']
)

task 6

In [29]:
# convert Date to datetime
avocado['Date'] = pd.to_datetime(avocado['Date'])

task 7

In [30]:
# verify changes
avocado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17911 entries, 0 to 18248
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          17911 non-null  datetime64[ns]
 1   AveragePrice  17911 non-null  float64
 2   Total Volume  17911 non-null  float64
 3   Total Bags    17911 non-null  float64
 4   Small Bags    17911 non-null  float64
 5   Large Bags    17911 non-null  float64
 6   XLarge Bags   17911 non-null  float64
 7   type          17911 non-null  object
 8   year          17911 non-null  int64
 9   region        17911 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(1), object(2)
memory usage: 1.5+ MB

In [31]:
avocado.head()

,Date,AveragePrice,Total Volume,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,6183.95,5986.26,197.69,0.0,conventional,2015,Albany