# Exercise 6-1: Clean the Polling Data

**CAP3321C - Data Wrangling**

---

## Overview

This exercise will guide you through the process of cleaning the Polling data for the 2016 election for president of the United States. As you clean that data, you'll use most of the procedures and methods presented in this chapter.

**Instructions:**
1. Run the setup cells to load the data
2. Complete each task by writing code in the provided cells
3. Some tasks are pre-filled - just run them and observe
4. Tasks marked with **YOUR CODE** require you to write the code

**Group Members:**
- Name 1:Ricardo
- Name 2:Ernesto
- Name 3:
- Name 4:

---

## Read the Data

Run these cells to load the data. Do not modify this section.

In [ ]:
import pandas as pd

In [ ]:
# Download the data file from GitHub
!wget -q https://raw.githubusercontent.com/c-marq/CAP3321C-Data-Wrangling/main/data/president_polls_2016.csv
print("Data file downloaded successfully!")

Data file downloaded successfully!

In [ ]:
# Load the polling data
polls = pd.read_csv('president_polls_2016.csv')
print("Data shape:", polls.shape)
polls.head()

Data shape: (12624, 27)

,cycle,branch,type,matchup,forecastdate,state,startdate,enddate,pollster,grade,...,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,multiversions,url,poll_id,question_id,createddate,timestamp
0,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,ABC News/Washington Post,A+,...,45.20163,41.72430,4.626221,NaN,NaN,https://www.washingtonpost.com/news/the-fix/wp...,48630,76192,11/7/16,09:35:33 8 Nov 2016
1,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/1/2016,11/7/2016,Google Consumer Surveys,B,...,43.34557,41.21439,5.175792,NaN,NaN,https://datastudio.google.com/u/0/#/org//repor...,48847,76443,11/7/16,09:35:33 8 Nov 2016
2,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/2/2016,11/6/2016,Ipsos,A-,...,42.02638,38.81620,6.844734,NaN,NaN,http://projects.fivethirtyeight.com/polls/2016...,48922,76636,11/8/16,09:35:33 8 Nov 2016
3,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/4/2016,11/7/2016,YouGov,B,...,45.65676,40.92004,6.069454,NaN,NaN,https://d25d2506sfb94s.cloudfront.net/cumulus_...,48687,76262,11/7/16,09:35:33 8 Nov 2016
4,2016,President,polls-plus,Clinton vs. Trump vs. Johnson,11/8/16,U.S.,11/3/2016,11/6/2016,Gravis Marketing,B-,...,46.84089,42.33184,3.726098,NaN,NaN,http://www.gravispolls.com/2016/11/final-natio...,48848,76444,11/7/16,09:35:33 8 Nov 2016

---

## Part 1: Examine the Data

Before cleaning data, you need to understand what you're working with.

### Task 4: Run the info() Method (YOUR CODE)

Run the `info()` method on the DataFrame. Make a note of the columns that have missing values.

**Hint:** Columns with missing values will show fewer non-null counts than the total number of rows.

**Expected output:** A summary showing column names, non-null counts, and data types

In [ ]:
# check the DataFrame information
polls.info(verbose=True, memory_usage='deep', show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12624 entries, 0 to 12623
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cycle             12624 non-null  int64
 1   branch            12624 non-null  object
 2   type              12624 non-null  object
 3   matchup           12624 non-null  object
 4   forecastdate      12624 non-null  object
 5   state             12624 non-null  object
 6   startdate         12624 non-null  object
 7   enddate           12624 non-null  object
 8   pollster          12624 non-null  object
 9   grade             11337 non-null  object
 10  samplesize        12621 non-null  float64
 11  population        12624 non-null  object
 12  poll_wt           12624 non-null  float64
 13  rawpoll_clinton   12624 non-null  float64
 14  rawpoll_trump     12624 non-null  float64
 15  rawpoll_johnson   8397 non-null   float64
 16  rawpoll_mcmullin  90 non-null     float64
 17  adjpoll_clinton   12624 non-null  float64
 18  adjpoll_trump     12624 non-null  float64
 19  adjpoll_johnson   8397 non-null   float64
 20  adjpoll_mcmullin  90 non-null     float64
 21  multiversions     36 non-null     object
 22  url               12621 non-null  object
 23  poll_id           12624 non-null  int64
 24  question_id       12624 non-null  int64
 25  createddate       12624 non-null  object
 26  timestamp         12624 non-null  object
dtypes: float64(10), int64(3), object(14)
memory usage: 11.7 MB

### Task 5: Run the nunique() Method (YOUR CODE)

Run the `nunique()` method on the DataFrame. Make a note of the columns with only one value.

**Hint:** Columns with only 1 unique value don't provide useful information for analysis.

**Expected output:** A Series showing the count of unique values for each column

In [ ]:
# count unique values in each column
polls.nunique()

cycle                   1
branch                  1
type                    3
matchup                 1
forecastdate            1
state                  57
startdate             352
enddate               345
pollster              196
grade                  10
samplesize           1766
population              4
poll_wt              4399
rawpoll_clinton      1312
rawpoll_trump        1385
rawpoll_johnson       584
rawpoll_mcmullin       16
adjpoll_clinton     12569
adjpoll_trump       12582
adjpoll_johnson      6629
adjpoll_mcmullin       57
multiversions           1
url                  1304
poll_id              4208
question_id          4208
createddate           222
timestamp               3
dtype: int64

---

## Part 2: Drop Columns and Rows

Remove unnecessary data to focus on what matters.

### Task 6: Filter Rows by Type (YOUR CODE)

Drop all rows **except** where the `type` column contains a value of `"now-cast"`.

**Hint:** Use `.query()` to filter rows, then reassign to `polls`.

**Example syntax:**
```python
polls = polls.query('column == "value"')
```

**Expected output:** The DataFrame should have fewer rows (only "now-cast" type polls)

In [ ]:
# keep only now-cast polls
polls = polls.query('type == "now-cast"')

### Task 7: Verify Rows Were Dropped (YOUR CODE)

Run the `nunique()` method again to make sure the rows have been dropped. This should show that the `adjpoll` columns have about one third as many rows as they did before.

**Expected output:** Reduced unique value counts, especially in adjpoll columns

In [ ]:
# check the unique values again
polls.nunique()

cycle                  1
branch                 1
type                   1
matchup                1
forecastdate           1
state                 57
startdate            352
enddate              345
pollster             196
grade                 10
samplesize          1766
population             4
poll_wt             3894
rawpoll_clinton     1312
rawpoll_trump       1385
rawpoll_johnson      584
rawpoll_mcmullin      16
adjpoll_clinton     4202
adjpoll_trump       4199
adjpoll_johnson     2210
adjpoll_mcmullin      30
multiversions          1
url                 1304
poll_id             4208
question_id         4208
createddate          222
timestamp              1
dtype: int64

### Task 8: Drop Columns with a Single Value (YOUR CODE)

Drop all columns with a single value. These columns don't provide useful information.

**Hint:**
- First, identify which columns have only 1 unique value from Task 7
- Use `.drop(columns=[list_of_columns])` to remove them
- Remember to reassign or use `inplace=True`

**Example syntax:**
```python
polls = polls.drop(columns=['col1', 'col2', 'col3'])
```

**Expected output:** DataFrame with fewer columns

In [ ]:
# drop columns with only one value
polls.drop(columns=['cycle','branch','type','matchup','forecastdate',
                    'multiversions','timestamp'],
           errors='raise', inplace=True)

### Task 9: Drop Rows Where State is "U.S." (YOUR CODE)

Drop all rows where the `state` column has a value of `"U.S."`. We want to focus on state-level polling data.

**Hint:** Use `.query()` with `!=` to keep rows that are NOT "U.S."

**Example syntax:**
```python
polls = polls.query('state != "U.S."')
```

**Expected output:** DataFrame without national-level polls

In [ ]:
# keep only state-level polls
polls = polls.query('state != "U.S."')

### Task 10: Verify with nunique() Again (YOUR CODE)

Run the `nunique()` method one more time to see how the values have changed.

**Expected output:** Updated unique value counts reflecting the cleaned data

In [ ]:
# check the unique values again
polls.nunique()

state                 56
startdate            245
enddate              241
pollster             176
grade                 10
samplesize          1308
population             4
poll_wt             2874
rawpoll_clinton     1162
rawpoll_trump       1217
rawpoll_johnson      578
rawpoll_mcmullin      16
adjpoll_clinton     3100
adjpoll_trump       3097
adjpoll_johnson     1672
adjpoll_mcmullin      30
url                  847
poll_id             3102
question_id         3102
createddate          185
dtype: int64

---

## Part 3: Rename Columns

Make column names more user-friendly.

### Task 11: Rename the rawpoll Columns (YOUR CODE)

Rename each `rawpoll_name` column to `name_pct` where *name* is the candidate's name. For example, rename the `rawpoll_clinton` column to `clinton_pct`.

**Hint:** Use the `.rename()` method with a dictionary mapping old names to new names.

**Example syntax:**
```python
polls = polls.rename(columns={
    'old_name1': 'new_name1',
    'old_name2': 'new_name2'
})
```

**Columns to rename:**
- `rawpoll_clinton` → `clinton_pct`
- `rawpoll_trump` → `trump_pct`
- `rawpoll_johnson` → `johnson_pct`
- `rawpoll_mcmullin` → `mcmullin_pct`

**Expected output:** DataFrame with renamed columns

In [ ]:
# rename rawpoll columns
polls = polls.rename(columns={
    'rawpoll_clinton':'clinton_pct',
    'rawpoll_trump':'trump_pct',
    'rawpoll_johnson':'johnson_pct',
    'rawpoll_mcmullin':'mcmullin_pct'
})

---

## Part 4: Fix Data Types

Convert columns to appropriate data types for analysis.

### Task 12: Check Current Data Types (YOUR CODE)

Run the `info()` method on the data to see the current data types.

**Expected output:** Notice that date columns are showing as `object` (string) type

In [ ]:
# check the current data types
polls.info(verbose=True, memory_usage='deep', show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 3102 entries, 4216 to 8415
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             3102 non-null   object
 1   startdate         3102 non-null   object
 2   enddate           3102 non-null   object
 3   pollster          3102 non-null   object
 4   grade             2961 non-null   object
 5   samplesize        3101 non-null   float64
 6   population        3102 non-null   object
 7   poll_wt           3102 non-null   float64
 8   clinton_pct       3102 non-null   float64
 9   trump_pct         3102 non-null   float64
 10  johnson_pct       2246 non-null   float64
 11  mcmullin_pct      30 non-null     float64
 12  adjpoll_clinton   3102 non-null   float64
 13  adjpoll_trump     3102 non-null   float64
 14  adjpoll_johnson   2246 non-null   float64
 15  adjpoll_mcmullin  30 non-null     float64
 16  url               3102 non-null   object
 17  poll_id           3102 non-null   int64
 18  question_id       3102 non-null   int64
 19  createddate       3102 non-null   object
dtypes: float64(10), int64(2), object(8)
memory usage: 1.8 MB

### Task 13: Create a List of Datetime Columns (YOUR CODE)

Create a list of columns that should use the datetime type. Look at the column names - which ones contain dates?

**Hint:** Look for columns with "date" in the name.

**Example syntax:**
```python
date_cols = ['col1', 'col2', 'col3']
```

**Expected output:** A list variable containing the names of date columns

In [ ]:
# list of date columns
date_cols = ['startdate', 'enddate', 'createddate']

### Task 14: Convert to Datetime (YOUR CODE)

Apply the Pandas `to_datetime()` method to the columns in the list of datetime columns to convert these columns to the datetime type.

**Hint:** Use a for loop to convert each column.

**Example syntax:**
```python
for col in date_cols:
    polls[col] = pd.to_datetime(polls[col])
```

**Expected output:** Date columns converted to datetime64 type

In [ ]:
# convert date columns to datetime
polls[date_cols] = polls[date_cols].apply(pd.to_datetime)

/tmp/ipykernel_3989/2572162394.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  polls[date_cols] = polls[date_cols].apply(pd.to_datetime)

In [ ]:
polls[date_cols].dtypes

startdate      datetime64[ns]
enddate        datetime64[ns]
createddate    datetime64[ns]
dtype: object

### Task 15: Convert to Category Type (YOUR CODE)

Convert the `state` and `population` columns to the category type. This is more memory-efficient for columns with a limited number of unique values.

**Hint:** Use `.astype('category')` to convert.

**Example syntax:**
```python
polls['column'] = polls['column'].astype('category')
```

**Expected output:** state and population columns converted to category type

In [ ]:
# convert state and population to category type
polls['state'] = polls['state'].astype('category')
polls['population'] = polls['population'].astype('category')

### Task 16: Verify Data Types (YOUR CODE)

Run the `info()` method one more time to see the new data types.

**Expected output:** Date columns showing as datetime64, state and population showing as category

In [ ]:
# verify the new data types
polls.info(verbose=True, memory_usage='deep', show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 3102 entries, 4216 to 8415
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             3102 non-null   category
 1   startdate         3102 non-null   datetime64[ns]
 2   enddate           3102 non-null   datetime64[ns]
 3   pollster          3102 non-null   object
 4   grade             2961 non-null   object
 5   samplesize        3101 non-null   float64
 6   population        3102 non-null   category
 7   poll_wt           3102 non-null   float64
 8   clinton_pct       3102 non-null   float64
 9   trump_pct         3102 non-null   float64
 10  johnson_pct       2246 non-null   float64
 11  mcmullin_pct      30 non-null     float64
 12  adjpoll_clinton   3102 non-null   float64
 13  adjpoll_trump     3102 non-null   float64
 14  adjpoll_johnson   2246 non-null   float64
 15  adjpoll_mcmullin  30 non-null     float64
 16  url               3102 non-null   object
 17  poll_id           3102 non-null   int64
 18  question_id       3102 non-null   int64
 19  createddate       3102 non-null   datetime64[ns]
dtypes: category(2), datetime64[ns](3), float64(10), int64(2), object(3)
memory usage: 1.1 MB

### Task 17: Display the Cleaned Data (YOUR CODE)

Display the Polls data to see how it looks after all the cleaning.

**Expected output:** A clean, well-organized DataFrame ready for analysis

In [ ]:
# display the cleaned data
polls

,state,startdate,enddate,pollster,grade,samplesize,population,poll_wt,clinton_pct,trump_pct,johnson_pct,mcmullin_pct,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,url,poll_id,question_id,createddate
4216,New Mexico,2016-11-06,2016-11-06,Zia Poll,NaN,8439.0,lv,4.609492,46.00,44.00,6.0,NaN,45.04927,41.92541,7.657972,NaN,http://projects.fivethirtyeight.com.s3.amazona...,48614,76158,2016-11-07
4221,Virginia,2016-11-03,2016-11-04,Public Policy Polling,B+,1238.0,lv,3.923524,48.00,43.00,1.0,NaN,47.45700,42.35281,2.199139,NaN,http://www.publicpolicypolling.com/pdf/2015/PP...,48349,75743,2016-11-04
4223,Iowa,2016-11-01,2016-11-04,Selzer & Company,A+,800.0,lv,3.842234,39.00,46.00,6.0,NaN,39.36898,45.67372,5.995712,NaN,http://www.desmoinesregister.com/story/news/po...,48470,75957,2016-11-05
4225,Wisconsin,2016-10-26,2016-10-31,Marquette University,A,1255.0,lv,3.789957,46.00,40.00,4.0,NaN,46.10277,41.02478,2.856997,NaN,https://twitter.com/MULawPoll,48095,75264,2016-11-02
4226,North Carolina,2016-11-04,2016-11-06,Siena College,A,800.0,lv,3.774139,44.00,44.00,3.0,NaN,44.26048,44.98719,2.236248,NaN,http://www.nytimes.com/2016/11/08/upshot/trump...,48524,76066,2016-11-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8411,North Carolina,2016-08-26,2016-08-27,Public Policy Polling,B+,1177.0,lv,0.000000,45.00,44.00,NaN,NaN,44.40263,44.69241,NaN,NaN,http://nelpaction.org/wp-content/uploads/2016/...,45261,69614,2016-09-01
8412,North Carolina,2016-03-09,2016-03-10,SurveyUSA,A,1576.0,lv,0.000000,42.00,49.00,NaN,NaN,38.91546,48.83620,NaN,NaN,http://www.highpoint.edu/blog/2016/03/hpu-poll...,36589,65523,2016-05-05
8413,North Carolina,2016-07-31,2016-08-02,SurveyUSA,A,400.0,lv,0.000000,42.00,46.00,6.0,NaN,42.90049,48.56213,3.223028,NaN,https://www.nccivitas.org/2016/civitas-release...,44759,68485,2016-08-03
8414,Utah,2016-08-05,2016-08-25,Ipsos,A-,177.0,lv,0.000000,33.67,38.53,NaN,NaN,33.17161,40.04859,NaN,NaN,http://www.reuters.com/statesofthenation,45033,69086,2016-08-26
8415,Missouri,2016-10-21,2016-11-02,Ipsos,A-,405.0,lv,0.000000,41.09,47.19,NaN,NaN,39.82209,46.82893,NaN,NaN,http://www.reuters.com/statesofthenation/,48236,75537,2016-11-03

---

## Summary

In this exercise, you practiced cleaning data:

**Examining Data:**
- `info()` - View column types and missing values
- `nunique()` - Count unique values per column

**Dropping Rows and Columns:**
- `query()` - Filter rows based on conditions
- `drop(columns=[...])` - Remove unnecessary columns

**Renaming Columns:**
- `rename(columns={...})` - Change column names

**Fixing Data Types:**
- `pd.to_datetime()` - Convert strings to datetime
- `astype('category')` - Convert to category type

---

**Submission:** Save this notebook and submit to Canvas before the deadline.